# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.3.1
  hooks:
    - id: nbqa-isort
      additional_dependencies: [isort==5.10.1]
    - id: nbqa-black
      additional_dependencies: [black==22.6.0]
    - id: nbqa-flake8
      additional_dependencies: [flake8==4.0.1]
