from pathlib import Path

import pygmo as pg
from utils import (
    get_all_optimisation_params,
    get_config,
    get_networks_save_dir,
    get_objectives,
    save_jsonpickle,
)

from spineq.data.fetcher import lad20nm_to_lad20cd
from spineq.genetic import build_problem, run_problem
from spineq.optimise import get_optimisation_inputs


def get_two_objs_filepath(config: dict) -> Path:
    """Get file path to save or load two-objective networks.

    Parameters
    ----------
    config : dict
        Parameters as loaded by utils.get_config

    Returns
    -------
    Path
        Path to save optimised networks to
    """
    networks_dir = get_networks_save_dir(config)
    filename = config["optimisation"]["two_objectives"]["filename"]
    return Path(networks_dir, filename)


def get_two_obj_inputs(
    lad20cd: str,
    objectives: list,
    population_groups: dict,
    workplace_name: str = "workplace",
) -> dict:
    """Get the inputs needed for the two-objective optimisation - the weights and
    location of each output area.

    Parameters
    ----------
    lad20cd : str
        Local authority code to generate results for
    objectives : str
        Names of the two objectives to include. Must be length two and names must match
        an entry in `population_groups` or `workplace_name`
    population_groups : dict
        Parameters for residential population objectives, as returned by
        utils.get_objectives
    workplace_name: str, optional
        Name of the place of work objective, by default "workplace"
    Returns
    -------
    dict
        Output area centroids and weights for each output area for each objective, as
        calculated by spineq.optimise.get_optimisation_inputs
    """
    if len(objectives) != 2:
        raise ValueError(f"Must define 2 objectives in config.yml. Got {objectives}")

    workplace_weight = 1 if workplace_name in objectives else 0
    return get_optimisation_inputs(
        lad20cd=lad20cd,
        population_weight=1,
        workplace_weight=workplace_weight,
        pop_age_groups={
            obj: population_groups[obj] for obj in objectives if obj != workplace_name
        },
        combine=False,
    )


def make_two_obj_networks(
    inputs: dict, thetas: list, n_sensors: list, gen: int, population_size: int
) -> dict:
    """Generate networks optimised for two objectives for a range of theta values
    (coverage distances) and numbers of sensors. Networks are generated with the
    NSGA2 algorithm.

    Parameters
    ----------
    inputs : dict
        Output area weights and locations as generated by get_two_obj_inputs
    thetas : list
        Theta (coverage distance) values to generate networks for
    n_sensors : list
        Generate networks with this many sensors
    gen : int
        Number of generations (iterations) to run the optimisation for
    population_size : int
        Number of candidate networks in each generation

    Returns
    -------
    dict
        Optimised networks and coverage scores
    """
    results = {}
    for t in thetas:
        results[f"theta{t}"] = {}
        for ns in n_sensors:
            print("theta", t, ", n_sensors", ns)
            prob = build_problem(inputs, n_sensors=ns, theta=t)
            pop = run_problem(
                prob,
                uda=pg.nsga2(gen=gen),
                population_size=population_size,
                verbosity=1,
            )
            results[f"theta{t}"][f"{ns}sensors"] = pop

    return results


def main():
    """
    Generate two-objective networks for a local authority and save them to the path
    specified in config.yml.
    """
    print("Generating two-objective networks...")
    config = get_config()
    lad20cd = lad20nm_to_lad20cd(config["la"])
    save_path = get_two_objs_filepath(config)

    population_groups, _ = get_objectives(config)
    thetas, n_sensors = get_all_optimisation_params(config)
    gen = config["optimisation"]["two_objectives"]["gen"]
    population_size = config["optimisation"]["two_objectives"]["population_size"]
    seed = config["optimisation"]["two_objectives"]["seed"]
    pg.set_global_rng_seed(seed=seed)
    objectives = config["optimisation"]["two_objectives"]["objectives"]
    inputs = get_two_obj_inputs(lad20cd, objectives, population_groups)

    results = make_two_obj_networks(inputs, thetas, n_sensors, gen, population_size)
    save_jsonpickle(results, save_path)


if __name__ == "__main__":
    main()
