name: Run tests and code quality checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run tests and quality checks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: spatial-inequality
          environment-file: environment.yml

      - name: Install dev dependencies
        run: pip install ".[dev]"
      - name: Check code style with black, isort and flake8
        run: |
          black --check .
          isort --check .
          flake8
          nbqa black --check .
          nbqa isort --check .
          nbqa flake8
      - name: Test with pytest
        run: pytest
